### ISSUE TITLE
How to handle old log files

### ISSUE THREAD

**Issue by stephanstapel** [exoscale/python-logstash-formatter#15]
Hi,

I just wanted to ask if there is a built-in mechanism or an idea how to handle log files after content has been shipped to Logstash. Can the created files be deleted or are the deleted automatically?

**Comment by pyr** [comment]
Hi @stephanstapel,

This is not a job for the formatter, so it doesn't concern itself with it. You could be using a handler that would directly ship to logstash over the network for instance, or just use a rolling appender and purge old files.

To be more specific, I would encourage you to look into python logging appenders.

cheers,
  - pyr
