### ISSUE TITLE
@message vs message

### ISSUE THREAD

**Issue by johnwheeler** [exoscale/python-logstash-formatter#21]
Hello,

I am looking at https://gist.github.com/jordansissel/2996677 and it appears that message is not preceded by the ampersand character in rubydebug, and in the gist, jordan alludes to that being the authoritative source for how to format the main json elements. 

I'm new to logstash so I don't know if there's just something I'm not understanding and would like to know your thoughts on this.

Regards,
John

**Comment by andrewmichaelsmith** [comment]
Thanks @remotesyssupport, would be helpful if this was mentioned somewhere in the docs. As someone just starting out with logstash I grabbed the latest version and was confused to find logstash_formatter not working as expected.

**Comment by pyr** [comment]
@andrewmichaelsmith thanks for noting this, the documentation has been updated.
