### ISSUE TITLE
Upload latest version to pypi

### ISSUE THREAD

**Issue by tinycogio** [exoscale/python-logstash-formatter#38]
Hello!

It would be awesome it if you can upload the latest version to pypi. Is this something you can tackle soon?

Thanks!

**Comment by mortenlj** [comment]
Any chance a new version could be released soon?

**Comment by muz** [comment]
It's been almost half a year since this issue was raised - any chance of getting a patch version out there soon as there's PRs in git that fix problems that I'm encountering in trying to use this library. :)

**Comment by brutasse** [comment]
0.5.15 is up on PyPI, sorry for the wait.

**Comment by muz** [comment]
Thanks!
